name: face_detection
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  google_mlkit_face_detection: ^0.9.0
  google_mlkit_commons: ^0.6.1
  get: 4.6.6
  flutter:
    sdk: flutter
  camera: ^0.10.5+7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
